export const ARTICLE_ALLOWED_URI_REGEXP =
  /^(?:(?:https?|mailto):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;

export const ARTICLE_SANITIZE_CONFIG = {
  ALLOWED_TAGS: [
    "a",
    "article",
    "aside",
    "audio",
    "b",
    "blockquote",
    "br",
    "code",
    "div",
    "em",
    "figcaption",
    "figure",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "iframe",
    "img",
    "li",
    "main",
    "ol",
    "p",
    "pre",
    "section",
    "small",
    "source",
    "span",
    "strong",
    "sub",
    "sup",
    "time",
    "u",
    "ul",
    "video",
  ],
  ALLOWED_ATTR: [
    "allow",
    "allowfullscreen",
    "alt",
    "aria-label",
    "class",
    "controls",
    "height",
    "href",
    "loading",
    "referrerpolicy",
    "rel",
    "src",
    "srcset",
    "target",
    "title",
    "type",
    "width",
  ],
  ALLOW_DATA_ATTR: false,
  FORBID_TAGS: ["form", "input", "button", "script", "style", "object", "embed"],
  FORBID_ATTR: ["style", "onerror", "onload", "onclick", "onmouseover"],
  ALLOWED_URI_REGEXP: ARTICLE_ALLOWED_URI_REGEXP,
};
